# Generated by Django 4.0.5 on 2022-09-13 02:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('info', '0003_company_is_contracted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(default='', max_length=500)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'manage_notice',
            },
        ),
        migrations.CreateModel(
            name='TenantBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.partnercontract')),
            ],
            options={
                'db_table': 'manage_tenant_bill',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(default='', max_length=100)),
                ('contents', models.CharField(default='', max_length=500)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manage_report',
            },
        ),
        migrations.CreateModel(
            name='PartnerBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.partnercontract')),
            ],
            options={
                'db_table': 'manage_partner_bill',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default='', max_length=10, null=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_handled', models.BooleanField(default=False)),
                ('img_url1', models.CharField(default='', max_length=100, null=True)),
                ('img_url2', models.CharField(default='', max_length=100, null=True)),
                ('img_url3', models.CharField(default='', max_length=100, null=True)),
                ('img_url4', models.CharField(default='', max_length=100, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manage_issue',
            },
        ),
    ]
