# Generated by Django 4.0.5 on 2022-09-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_remove_roomcontract_agent_and_more'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbill',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.roomcontract'),
        ),
    ]
