# Generated by Django 4.0.5 on 2022-09-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_company_is_contracted'),
        ('management', '0002_alter_tenantbill_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='contents',
            new_name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.company'),
            preserve_default=False,
        ),
    ]
