# Generated by Django 4.0.5 on 2022-09-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_company_ceo_name_company_ceo_phone_number_and_more'),
        ('management', '0003_rename_contents_report_pdf_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='MonthlyReport',
        ),
        migrations.AlterModelTable(
            name='monthlyreport',
            table='manage_monthly_report',
        ),
    ]
