# Generated by Django 4.0.5 on 2022-09-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_report_monthlyreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
    ]
