# Generated by Django 4.1.1 on 2022-09-21 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_issue_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_img1_url', models.CharField(max_length=500, null=True)),
                ('before_img2_url', models.CharField(max_length=500, null=True)),
                ('before_img3_url', models.CharField(max_length=500, null=True)),
                ('after_img_url1', models.CharField(max_length=500, null=True)),
                ('after_img_url2', models.CharField(max_length=500, null=True)),
                ('after_img_url3', models.CharField(max_length=500, null=True)),
                ('pdf_url', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.issue')),
            ],
            options={
                'db_table': 'manage_issue_report',
            },
        ),
    ]
