# Generated by Django 4.1.1 on 2022-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0007_issuereport_result_alter_issuereport_after_img_url1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantbill",
            name="paid_amount",
            field=models.IntegerField(default=0),
        ),
    ]
