# Generated by Django 4.1.1 on 2022-09-26 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_tenantbill_paid_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantbill",
            name="paid_date",
            field=models.DateField(default=datetime.date(2022, 9, 26)),
        ),
    ]
