# Generated by Django 4.0.2 on 2022-09-26 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_tenantbill_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbill',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 11, 14, 40, 686559, tzinfo=utc)),
        ),
    ]
