# Generated by Django 4.1.1 on 2022-09-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_alter_tenantbill_paid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantbill",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
