# Generated by Django 4.1.1 on 2022-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0012_tenantbill_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantbill",
            name="paid_date",
            field=models.DateField(null=True),
        ),
    ]
