# Generated by Django 4.1.1 on 2022-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_alter_tenantbill_paid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantbill",
            name="issued_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tenantbill",
            name="paid_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
