# Generated by Django 4.1.1 on 2022-09-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0016_tenantbill_whole_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnknownTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("amount", models.IntegerField(default=0)),
                ("whole_text", models.CharField(default="", max_length=500)),
            ],
            options={
                "db_table": "manage_unknown_transaction",
            },
        ),
    ]
