# Generated by Django 4.1.1 on 2022-10-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0012_alter_buildingcontract_sales_person"),
        ("management", "0018_alter_tenantbill_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contract.roomcontract",
            ),
            preserve_default=False,
        ),
    ]
