# Generated by Django 4.1.1 on 2022-10-11 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0019_issue_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issuereport",
            old_name="before_img1_url",
            new_name="before_img_url1",
        ),
        migrations.RenameField(
            model_name="issuereport",
            old_name="before_img2_url",
            new_name="before_img_url2",
        ),
        migrations.RenameField(
            model_name="issuereport",
            old_name="before_img3_url",
            new_name="before_img_url3",
        ),
    ]
