# Generated by Django 4.1.1 on 2022-10-11 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0020_rename_before_img1_url_issuereport_before_img_url1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreport",
            name="uploaded_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
