# Generated by Django 4.1.1 on 2022-10-13 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0023_alter_notification_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
