# Generated by Django 4.1.1 on 2022-10-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0024_notification_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="issue_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.issuereport",
            ),
        ),
    ]
