# Generated by Django 4.1.1 on 2022-10-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0025_notification_issue_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="title",
        ),
    ]
