# Generated by Django 4.1.1 on 2022-11-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0026_remove_issue_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="issue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.issue",
            ),
        ),
    ]
