# Generated by Django 4.1.1 on 2022-11-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0027_notification_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="monthly_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.monthlyreport",
            ),
        ),
    ]
