# Generated by Django 4.1.1 on 2022-11-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0028_notification_monthly_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(default="", max_length=20),
        ),
    ]
