# Generated by Django 4.0.6 on 2022-11-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeTenantBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('paid_date_time', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.IntegerField(default=0)),
                ('whole_text', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'manage_whole_tenant_bill',
            },
        ),
    ]
