# Generated by Django 4.1.1 on 2022-11-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0030_wholetenantbill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unknowntransaction",
            old_name="amount",
            new_name="paid_amount",
        ),
        migrations.AddField(
            model_name="unknowntransaction",
            name="paid_date",
            field=models.DateField(auto_now=True),
        ),
    ]
