# Generated by Django 4.1.1 on 2022-11-09 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0016_merge_20221108_0017"),
        ("management", "0032_issuereport_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuereport",
            name="contract",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contract.partnercontract",
            ),
        ),
    ]
