# Generated by Django 4.1.1 on 2022-11-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0037_monthlyreportimage_month_monthlyreportimage_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="img_url5",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
