# Generated by Django 4.1.1 on 2022-11-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0038_issue_img_url5"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreport",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="week",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="year",
            field=models.IntegerField(default=1),
        ),
    ]
