# Generated by Django 4.1.1 on 2022-11-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0040_monthlyreport_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerbill",
            name="monthly_charge",
            field=models.IntegerField(default=0),
        ),
    ]
