# Generated by Django 4.1.1 on 2022-11-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0041_partnerbill_monthly_charge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlyreport",
            old_name="content",
            new_name="comment",
        ),
    ]
