# Generated by Django 4.1.1 on 2022-11-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0042_rename_content_monthlyreport_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuereport",
            name="after_img_url1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="after_img_url2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="after_img_url3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="before_img_url1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="before_img_url2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="before_img_url3",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
