# Generated by Django 4.0.6 on 2023-03-07 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0035_alter_buildingcontract_rep'),
        ('management', '0045_repairreport_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='week',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='year',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='doc_url1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.buildingcontract'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
