# Generated by Django 4.0.6 on 2023-03-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_rename_created_at_monthlyreport_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbill',
            name='paid_amount',
        ),
    ]
