# Generated by Django 4.0.6 on 2023-03-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_remove_tenantbill_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbill',
            name='monthly_charge',
        ),
    ]
