# Generated by Django 4.0.6 on 2023-03-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_remove_tenantbill_monthly_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbill',
            name='month',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tenantbill',
            name='monthly_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantbill',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
